spring:
  application:
    name: features
  datasource:
    url: jdbc:mysql://localhost:3306/springboot_features
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


spring.jpa.properties.hibernate.format_sql: true

spring.devtools.restart.enabled : true
spring.devtools.restart.exclude:

server.port: 9000
employeeService.base.url: http://localhost:8080

#logging conf
logging.level.com.springboot.features.client: TRACE
logging.pattern.console: "%d{dd-MM-yyyy HH:mm:ss} [%thread]  %highlight(%-5level)  %logger{36} - %msg%n"
logging.file.name: application.log
logging.config: classpath:logback-spring.xml
#logging.level.root: INFO


#actuator confs
management:
  info:
    java:
      enabled: true
    defaults:
      enabled: true
    git:
      enabled: true
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

info:
  app:
    author: rsarakeri@gmail.com
    documentation: NA
    version: 1.0.0-SNAPSHOT


#security confs

spring.security.user.name: rahul
spring.security.user.password: rahul
spring.security.user.roles : ADMIN

jwt.scretKey: hbv342hb4u23hb23uir09fusjdf34fmsndfasdg34523f3e8ujoionsdqwqASDAW213ad