spring:
  application:
    name: features
  datasource:
    url: jdbc:mysql://localhost:3306/springboot_features
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


spring.jpa.properties.hibernate.format_sql: true

spring.devtools.restart.enabled : true
spring.devtools.restart.exclude:

server.port: 9000
employeeService.base.url: http://localhost:8080

#logging conf
logging.level.com.springboot.features.client: TRACE
logging.pattern.console: "%d{dd-MM-yyyy HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
logging.file.name: application.log
logging.config: classpath:logback-spring.xml
#logging.level.root: INFO